language: python

arch:
  - amd64
  - ppc64le
sudo: false

python:
  - "pypy"
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - RADIX_NO_EXT=true
  - RADIX_NO_EXT=false

matrix:
  exclude:
    - python: "pypy"  # pypy will always build without extension
      env: RADIX_NO_EXT=false
    - python: "pypy"  #poweron support exclude
      arch: ppc64le

install:
  - pip install coveralls 
  - python setup.py install

script:
  - python setup.py nosetests

after_success:
  - coveralls
